apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: frontend
    env: production
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
      - containerPort: 80
        name: http
      resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
