apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
  namespace: mini-olx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi