apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: mini-olx
spec:
  type: ClusterIP
  ports:
    - name: db-service
      port: 33061
      targetPort: 3306
  selector:
    app: db