apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: mini-olx
spec:
  type: NodePort
  ports:
    - name: frontend-service
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31001
  selector:
    app: frontend